### ISSUE TITLE
vscode failure

### ISSUE THREAD

**Issue by sylvainmetayer** [sylvainmetayer/dotfiles#16]
https://github.com/gantsign/ansible-role-visual-studio-code

**Comment by sylvainmetayer** [comment]
```

- name: install VS Code repo (dnf)
  become: yes
  yum_repository:
    name: code
    description: Visual Studio Code repo
    file: vscode
    baseurl: '{{ visual_studio_code_mirror }}/yumrepos/vscode'
    gpgkey: '{{ visual_studio_code_mirror }}/keys/microsoft.asc'
    gpgcheck: yes

```
